### ISSUE TITLE
Minimal Notebook

### ISSUE THREAD

**Issue by AmeenAli** [FarnoushRJ/MambaLRP#1]
Hi!

Great Work!!

Any chance you can publish a minimal Notebook for LLMs? (loading the models and applying LRP)

**Comment by FarnoushRJ** [comment]
Hi,

Thanks for your interest in our work!

I've added a minimal [Jupyter Notebook](https://github.com/FarnoushRJ/MambaLRP/blob/main/minimal_demo.ipynb) to the repository.

**Comment by chengyi-chris** [comment]
Hi! Thank you for your outstanding work!

I was wondering if there are any plans to release a minimal Jupyter notebook for the Vision Mamba versions in the repository.
The visualization of the pre-trained model as shown in the README.md
